services:
  postgre:
    image: postgres:alpine3.20
    container_name: postgre
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  frontend:
    build: 
      context: .
      dockerfile: frontend.dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - postgre
      - backend
    environment:
      - 'NUXT_PUBLIC_API_URL=${BACKEND_URL}'

  backend:
    build: 
      context: .
      dockerfile: backend.dockerfile
    container_name: backend
    restart: always
    environment:
      - 'DB_HOST=${DB_HOST}'
      - 'DB_PORT=${DB_PORT}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'HASH=${HASH}'
      - 'ORIGINS=${BACKEND_ORIGINS}'
    ports:
      - "3300:3300"
    networks:
      - default
    depends_on:
      - postgre

networks:
  default:
    driver: bridge
